# -*- coding: utf-8 -*-
"""MLproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NNH9N5_Y3Iw3vIIkSv63HkMRLYf2DUHE
"""

# Step 1: Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import pickle

 
# Step 2: Load Dataset
df = pd.read_csv("dataset.csv")   # update file name if needed
df.head()

# Step 3: Preprocessing
df.drop(columns=["ID"], errors='ignore', inplace=True)
df = df.dropna()

encoders = {}
X = df.drop("Time Taken (hrs)", axis=1).copy()
for col in X.select_dtypes(exclude=['number']).columns:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])
    encoders[col] = le

# Step 4: Define Features and Target
y = df["Time Taken (hrs)"]

# Step 5: Split Dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Step 6: Train Decision Tree
dt_model = DecisionTreeRegressor(random_state=42)
dt_model.fit(X_train, y_train)

# Step 7: Train Random Forest
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)


# Step 8: Predictions
dt_pred = dt_model.predict(X_test)
rf_pred = rf_model.predict(X_test)

# Step 9: Evaluation

def evaluate_model(y_true, y_pred, model_name):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)

    print(f"\n{model_name} Performance:")
    print(f"MAE: {mae}")
    print(f"RMSE: {rmse}")
    print(f"R2 Score: {r2}")


evaluate_model(y_test, dt_pred, "Decision Tree")
evaluate_model(y_test, rf_pred, "Random Forest")
 
# Save model and encoders
with open("model.pkl", "wb") as f:
    pickle.dump(rf_model, f)
with open("encoders.pkl", "wb") as f:
    pickle.dump(encoders, f)
# Store results
models = ["Decision Tree", "Random Forest"]

mae_scores = [
    mean_absolute_error(y_test, dt_pred),
    mean_absolute_error(y_test, rf_pred)
]

rmse_scores = [
    np.sqrt(mean_squared_error(y_test, dt_pred)),
    np.sqrt(mean_squared_error(y_test, rf_pred))
]

r2_scores = [
    r2_score(y_test, dt_pred),
    r2_score(y_test, rf_pred)
]

# 📊 Plot MAE
plt.figure()
plt.bar(models, mae_scores)
plt.title("MAE Comparison")
plt.xlabel("Models")
plt.ylabel("MAE")
plt.show()


# 📊 Plot RMSE
plt.figure()
plt.bar(models, rmse_scores)
plt.title("RMSE Comparison")
plt.xlabel("Models")
plt.ylabel("RMSE")
plt.show()


# 📊 Plot R2 Score
plt.figure()
plt.bar(models, r2_scores)
plt.title("R2 Score Comparison")
plt.xlabel("Models")
plt.ylabel("R2 Score")
plt.show()

